define({
  music: ['BWW_Tune1_V5', 0, 0.7],
  winTerminator: ['WinPresentation_V1_Slow_Short', 1],
  loseTerminator: ['LosePresentation_V1_Slow_Short', 1],
  click: ['Generic click', 4],
  costDown: ['Bet_Minus', 1],
  costUp: ['Bet_Plus', 2],
  bonusWin: ['Bonus Reveal-win', 2],
  bonusNoWin: ['Bonus Reveal-lose', 2],
  costMax: ['Bet_Max', 3],
  winningNumber: ['Lucky Number Reveal 1', 3],
  winningNumber_2: ['Lucky Number Reveal 2', 5],
  playerNumber: ['Your Number Reveal 1-SuitcaseClasp', 4],
  playerNumber_2: ['Your Number Reveal 2-SuitcaseClasp', 3],
  playerNumber_3: ['Your Number Reveal 3-SuitcaseClasp', 5],
  playerNumber_4: ['Your Number Reveal 4-SuitcaseClasp', 6],
  playerNumber_5: ['Your Number Reveal 5-SuitcaseClasp', 7],
  match: ['NumberMatchV3_2', 1],
});
